#!/usr/bin/env python3
"""
Generate Open-tasks.md from GitHub issues labeled "help wanted"
across all Flipper One repositories.

Requires: gh CLI (https://cli.github.com/) authenticated with GitHub.

Usage:
    python3 tools/generate_open_tasks.py > docs/Open-tasks.md
"""

import json
import subprocess
import sys
from textwrap import shorten

# Repository definitions: (slug, display name, project URL, description)
REPOS = [
    ("flipperdevices/flipperone-hardware",
     "Hardware",
     "https://github.com/orgs/flipperdevices/projects/9",
     "Electrical hardware development: printed circuit boards (PCBs), antennas, and everything related to the electrical design"),
    ("flipperdevices/flipperone-mechanics",
     "Mechanics",
     "https://github.com/orgs/flipperdevices/projects/15",
     "Mechanical design: enclosures, buttons, connectors, and everything related to the physical construction"),
    ("flipperdevices/flipperone-mcu-firmware",
     "MCU Firmware",
     "https://github.com/orgs/flipperdevices/projects/8",
     "Firmware for the RP2350 co-processor: FreeRTOS, display, buttons, touchpad, LEDs, and power management"),
    ("flipperdevices/flipperone-linux-build-scripts",
     "Linux (CPU Software)",
     "https://github.com/orgs/flipperdevices/projects/11",
     "Build system for the Linux firmware: U-Boot, kernel, root filesystem, and bootable images for the RK3576"),
    ("flipperdevices/flipperone-ui",
     "User Interface",
     "https://github.com/orgs/flipperdevices/projects/12",
     "User interface design: operating modes, on-screen graphics, device prints, and FlipCTL"),
    ("flipperdevices/flipperone-testing",
     "Testing",
     "https://github.com/orgs/flipperdevices/projects/14",
     "Hardware validation and test scripts: temperature monitoring, power, CPU, GPU, network, and disk tests"),
    ("flipperdevices/flipperone-docs",
     "Docs",
     "https://github.com/orgs/flipperdevices/projects/10",
     "Developer documentation published at docs.flipper.net/one"),
]

LABEL = "help wanted"
ORG = "flipperdevices"


def fetch_issues():
    """Fetch all open 'help wanted' issues across the org."""
    result = subprocess.run(
        [
            "gh", "search", "issues",
            "--owner", ORG,
            "--label", LABEL,
            "--state", "open",
            "--limit", "200",
            "--json", "repository,title,number,url,body,commentsCount",
        ],
        capture_output=True, text=True, check=True,
    )
    return json.loads(result.stdout)


def make_summary(body, max_len=120):
    """Extract first meaningful line of issue body as a short summary."""
    if not body:
        return ""
    for line in body.splitlines():
        line = line.strip()
        # Skip empty lines, images, headings, links-only lines
        if not line:
            continue
        if line.startswith(("![", "<img", "http://", "https://", "#")):
            continue
        # Clean up markdown formatting
        line = line.lstrip("*_-•> ")
        if len(line) < 5:
            continue
        return shorten(line, width=max_len, placeholder="...")
    return ""


def generate_page(issues):
    """Generate the markdown page content."""
    # Group issues by repo
    by_repo = {}
    for issue in issues:
        repo_full = issue["repository"]["nameWithOwner"]
        by_repo.setdefault(repo_full, []).append(issue)

    lines = []
    lines.append("# \U0001f6a7 Open tasks")
    lines.append("")
    lines.append("This page lists open tasks across all Flipper One repositories that are looking for contributors.")
    lines.append("All issues are labeled `help wanted` in their respective repos.")
    lines.append("")
    lines.append("<!-- Auto-generated by tools/generate_open_tasks.py — do not edit manually -->")
    lines.append("<!-- See: https://github.com/flipperdevices/flipperone-docs/issues/53 -->")
    lines.append("")

    for repo_slug, display_name, project_url, description in REPOS:
        repo_issues = by_repo.get(repo_slug, [])

        if not repo_issues:
            continue

        lines.append(f"## [{display_name}]({project_url})")
        lines.append(f"_{description}_")
        lines.append("")

        # Sort by issue number descending (newest first)
        repo_issues.sort(key=lambda i: i["number"], reverse=True)

        lines.append("| Task | Comments |")
        lines.append("|------|:--------:|")
        for issue in repo_issues:
            title = issue["title"]
            url = issue["url"]
            comments = issue["commentsCount"]
            summary = make_summary(issue.get("body", ""))

            cell = f"**[{title}]({url})**"
            if summary:
                cell += f" <br> {summary}"
            comment_str = str(comments)
            lines.append(f"| {cell} | {comment_str} |")

        lines.append("")

    return "\n".join(lines)


def main():
    issues = fetch_issues()
    page = generate_page(issues)
    print(page)


if __name__ == "__main__":
    main()
